{% set name = "sos-julia" %}
{% set version = "0.18.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2c67e0d18f54eaeebaaf11537b03d753206711debaf04c7c1673ecd3ae962bc

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
    - export JUPYTER_DATA_DIR=${PREFIX}/share/jupyter
    - export JUPYTER=$(which jupyter)
    - julia -e "using Pkg;Pkg.add([\"IJulia\", \"Feather\", \"DataFrames\", \"NamedArrays\"])"

requirements:
  host:
    - pip
    - python >=3.6
    - julia
  run:
    - sos-notebook >=0.19.4
    - feather-format
    - julia
    - python >=3.6

test:
  requires:
    - nose
    - pytest
    - selenium
  imports:
    - sos_julia

about:
  home: https://github.com/vatlab/sos-julia
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for Julia
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-julia

extra:
  recipe-maintainers:
    - BoPeng
