travis:
  secure:
    BINSTAR_TOKEN: Vn3OtoSL3j61wb0JSCiOo/3eIz6Ymf1ptV7XUPe83YsOazj1EJRAXDB0rqJ/FItn9PBAOJMjbjhn8IpzbPUu3eYK9HNj4c5UmSt7SQsE+gbTDdEW0mGeF/AWk44RGVUv5/GL//zJ1+zTveB7C03lnt2MHEesvw+wgow9VaqrYHOoL3nMgzjQfObp9PUGTVzkMlVnEfYfTZn7twEPcdsZOw9cvcK8NvLW5gUTP4dqV9XSwvfD+1ZaplTMTAQKrUxcUxkHC1ozC44kTheQpXwNKcirSrRmnCQ2w7CHk1ONbuR2OkHvpkfT6zua3d78z///iTlZFZtNKWx9fyx6FdPiuU72BetyVtFhdGfjHen7N7Qu7YPvuy05Wl3Wz4B4LVvyFT/zMcckUy/IzqEGdWEVsjAsC+vaqGsRJ81af6KWBw4ceUUuhR92IhjyOu7X/yIf0CZJAqhPIJNLcuVuMN8G9rDzMtYJWX6aC9MeBcpb33DBcuAvySAag8jn6BDoVDBpzdbP31uHl4mj8z2YfmnmFUs15aqx7rjIaG7zmrQkKCO4RI68iSI0jkWu1nKE/Ro5LB3mOIAzgjYBw1ClfXR7xI4rDCy+Y4CQ/sLtKTnxrTc0YXnsGzOG4KwmIQDER9C++goSQZlmkqSu0iokTksetUjSWIHAGrmRihw/4qUCkPA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
