travis:
  secure:
    BINSTAR_TOKEN: we/Wu+IT53s1kJzh8nNMlV5AfqsY18EOJPNX/xS++vz7ef0bgyn8Ma17w9l4OgVUMBXEWKjmTSJaQDm2tGKR8hgpTbeePac3jSbR3hKkpKz+2r3OZFUHv8a4dVZrc6oatL6yFI021L2shNEl4fMokLbrTKp+7vccVAgMVwttiM6ysxgjymZhlSawreALdWkn0Rgh0p3vz/M+cz4yQ98wEDnS62B+jGqHy61MbvADfFXwMD7aCL96BOHauUnPDVEyfMgxrzRUJ3OrSUli2OwFSMJ07W6zX3rKew/CRupcH0CN9wqd5QQZ82i6KnZYPG1dXURMh/uS2/PKbgVavbrY4jCj+hhF7oat4lX73D2J9/cFPbKwLvkeYTfUaVcnYwmewefqTe6CD3fS4IFU6IeNgqkqLEcwq3JfFr0gpC8vVxE+VQVWkWcke+HimbovK4QH0o4RS/IZnIAfa6nQdG5vAL5ELulJFw3y/d5l+RB5UE/pIOHCtKgedL8mmfTOSpYpTcQVVB9iMisnVcGsn7EH3pBuCFr1cKGRbimUmx/om3NbaeAVXPRmm2mmE0DbDuVwccEA6yB3VDMIPW2SPfDro9iTsdFAK/K/PHn1m0fjWTow3pT+0Enmnr1e9QZXUYPRvpgGqq+R/OtIt9HaSXMt+704B8jJgF+3BC68/Tpv34U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
